# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Controller.ClienteController import ClienteController

class Ui_MainWindow(object):

    def __init__(self):
        self.clienteController = ClienteController()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 294)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcluir.setGeometry(QtCore.QRect(250, 170, 75, 23))
        self.btnExcluir.setObjectName("btnExcluir")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(90, 170, 75, 23))
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnConsultar = QtWidgets.QPushButton(self.centralwidget)
        self.btnConsultar.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.btnConsultar.setObjectName("btnConsultar")
        self.edtEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.edtEndereco.setGeometry(QtCore.QRect(60, 70, 381, 21))
        self.edtEndereco.setObjectName("edtEndereco")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.edtCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.edtCpf.setGeometry(QtCore.QRect(60, 100, 171, 20))
        self.edtCpf.setObjectName("edtCpf")
        self.btnAtualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizar.setGeometry(QtCore.QRect(170, 170, 75, 23))
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_3.setObjectName("label_3")
        self.edtNome = QtWidgets.QLineEdit(self.centralwidget)
        self.edtNome.setGeometry(QtCore.QRect(60, 40, 381, 20))
        self.edtNome.setObjectName("edtNome")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.edtId = QtWidgets.QLineEdit(self.centralwidget)
        self.edtId.setGeometry(QtCore.QRect(60, 10, 111, 20))
        self.edtId.setObjectName("edtId")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_5.setObjectName("label_5")
        self.edtTelefone = QtWidgets.QLineEdit(self.centralwidget)
        self.edtTelefone.setGeometry(QtCore.QRect(60, 130, 171, 20))
        self.edtTelefone.setObjectName("edtTelefone")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btnConsultar.clicked.connect(self.consultar)
        self.btnCadastrar.clicked.connect(self.cadastrar)
        self.btnAtualizar.clicked.connect(self.atualizar)
        self.btnExcluir.clicked.connect(self.excluir)

    def consultar(self):
        dados = self.clienteController.consultar(int(self.edtId.text()))
        if dados:
            self.edtNome.setText(dados[1])
            self.edtEndereco.setText(dados[2])
            self.edtCpf.setText(dados[3])
            self.edtTelefone.setText(dados[4])
            self.btnCadastrar.setEnabled(False)
            self.btnAtualizar.setEnabled(True)
            print("Consultado valores!")
        else:
            self.edtNome.setText('')
            self.edtEndereco.setText('')
            self.edtCpf.setText('')
            self.edtTelefone.setText('')
            print("Não foi possivel consultar!")

    def cadastrar(self):
        if self.clienteController.cadastrar(int(self.edtId.text()),
                                         self.edtNome.text(),
                                         self.edtEndereco.text(),
                                         self.edtCpf.text(),
                                         self.edtTelefone.text()):
            print('Cliente cadastrado!')
            self.edtId.setText('')
            self.edtNome.setText('')
            self.edtEndereco.setText('')
            self.edtCpf.setText('')
            self.edtTelefone.setText('')

        else:
            self.edtId.setText('')
            print('Erro ao cadastrar Cliente!')

    def atualizar(self):
        if self.clienteController.atualizar(str(self.edtId.text()),
                                            self.edtNome.text(),
                                            self.edtEndereco.text(),
                                            self.edtCpf.text(),
                                            self.edtTelefone.text()):
            print('Cliente atualizado!')

            self.edtId.setText('')
            self.edtNome.setText('')
            self.edtEndereco.setText('')
            self.edtCpf.setText('')
            self.edtTelefone.setText('')
            self.btnCadastrar.setEnabled(True)
        else:
            print('Erro ao atualizar Cliente!')

    def excluir(self):
        if self.clienteController.excluir(self.edtId.text()):
            print('Cliente excluído!')
            self.edtId.setText('')
            self.edtNome.setText('')
            self.edtEndereco.setText('')
            self.edtCpf.setText('')
            self.edtTelefone.setText('')
            self.btnCadastrar.setEnabled(True)
        else:
            print('Erro ao excluir Cliente!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnExcluir.setText(_translate("MainWindow", "Excluir"))
        self.btnCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.btnConsultar.setText(_translate("MainWindow", "Consultar"))
        self.label_4.setText(_translate("MainWindow", "CPF"))
        self.btnAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.label.setText(_translate("MainWindow", "Código"))
        self.label_3.setText(_translate("MainWindow", "Endereço"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.label_5.setText(_translate("MainWindow", "Telefone"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
